<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class BJM_Candidate_Dashboard {
    public static function init() { add_shortcode( 'bjm_candidate_dashboard', array( __CLASS__, 'render' ) ); }
    public static function render() {
        if ( ! is_user_logged_in() ) return self::render_guest_alert_dashboard();
        $tab=sanitize_key(wp_unslash($_GET['bjm_tab']??'saved'));$base_url=bjm_get_page_url('candidate_dashboard_page_id')?:get_permalink();$saved_jobs=bjm_get_saved_job_posts();$alerts=bjm_get_job_alerts_for_user();$editing_alert=isset($_GET['alert_id'])?bjm_get_job_alert(absint($_GET['alert_id'])):null;
        ob_start();echo bjm_render_notices();echo '<div class="bjm-dashboard-wrap bjm-dashboard-theme bjm-candidate-dashboard"><div class="bjm-panel bjm-dashboard-hero"><div class="bjm-panel-head"><div><h3>Candidate Dashboard</h3><p class="bjm-hero-sub">Save jobs you want to come back to, track your alerts, and keep your job search organised.</p></div></div><div class="bjm-stats-grid bjm-stats-grid-lg">';
        echo '<div class="bjm-stat-card"><div class="bjm-stat-label">Saved Jobs</div><div class="bjm-stat-value">'.esc_html(count($saved_jobs)).'</div></div><div class="bjm-stat-card"><div class="bjm-stat-label">Active Alerts</div><div class="bjm-stat-value">'.esc_html(count(array_filter($alerts,function($alert){return isset($alert->status)&&'active'===$alert->status;}))).'</div></div><div class="bjm-stat-card"><div class="bjm-stat-label">Tracked Alerts</div><div class="bjm-stat-value">'.esc_html(count($alerts)).'</div></div><div class="bjm-stat-card"><div class="bjm-stat-label">Dashboard Status</div><div class="bjm-stat-value">Ready</div></div></div>';
        echo '<div class="bjm-tab-nav"><a class="bjm-tab '.('saved'===$tab?'is-active':'').'" href="'.esc_url(add_query_arg('bjm_tab','saved',$base_url)).'">Saved Jobs</a><a class="bjm-tab '.('alerts'===$tab?'is-active':'').'" href="'.esc_url(add_query_arg('bjm_tab','alerts',$base_url)).'">Job Alerts</a></div>';
        if('alerts'===$tab)self::render_alert_manager($alerts,$editing_alert,$base_url,true);else if($saved_jobs){echo '<div class="bjm-job-grid">';foreach($saved_jobs as $job){$remove_link=wp_nonce_url(add_query_arg(array('bjm_tab'=>'saved','bjm_unsave_job'=>$job->ID),$base_url),'bjm_unsave_job');echo '<article class="bjm-job-card"><div class="bjm-card-head"><h4><a href="'.esc_url(get_permalink($job->ID)).'">'.esc_html(get_the_title($job->ID)).'</a></h4><span class="bjm-pill">Saved</span></div><div class="meta">'.esc_html((string)get_post_meta($job->ID,'_bjm_company_name',true)).'</div><div class="bjm-excerpt">'.esc_html(wp_trim_words(wp_strip_all_tags($job->post_excerpt?$job->post_excerpt:$job->post_content),22)).'</div><p><a class="button" href="'.esc_url(get_permalink($job->ID)).'">View job</a> <a class="button" href="'.esc_url($remove_link).'">Remove</a></p></article>';}echo '</div>';}else echo '<p>No saved jobs yet. Save jobs from the listings page or individual job pages.</p>';
        echo '</div></div>';return ob_get_clean();
    }
    private static function render_guest_alert_dashboard(){ $base_url=bjm_get_page_url('candidate_dashboard_page_id')?:get_permalink();$manage_token=sanitize_text_field(wp_unslash($_GET['bjm_guest_alert']??''));$editing_alert=$manage_token?bjm_get_guest_alert_by_manage_token($manage_token):null;$alerts=$editing_alert?bjm_get_job_alerts_for_email($editing_alert->email):array();ob_start();echo bjm_render_public_notice();echo '<div class="bjm-dashboard-wrap bjm-dashboard-theme bjm-candidate-dashboard bjm-guest-dashboard"><div class="bjm-panel bjm-dashboard-hero"><div class="bjm-panel-head"><div><h3>Job Alerts</h3><p class="bjm-hero-sub">Create alerts without an account, or <a href="'.esc_url(wp_login_url($base_url)).'">log in</a> to save jobs and manage everything from your dashboard.</p></div></div><div class="bjm-stats-grid bjm-stats-grid-lg"><div class="bjm-stat-card"><div class="bjm-stat-label">Guest Alerts</div><div class="bjm-stat-value">'.esc_html(count($alerts)).'</div></div><div class="bjm-stat-card"><div class="bjm-stat-label">Verification</div><div class="bjm-stat-value">Email</div></div><div class="bjm-stat-card"><div class="bjm-stat-label">Management</div><div class="bjm-stat-value">Magic Link</div></div></div>';self::render_alert_manager($alerts,$editing_alert,$base_url,false);echo '</div></div>';return ob_get_clean(); }
    private static function render_alert_manager($alerts,$editing_alert,$base_url,$logged_in){$categories=bjm_get_available_job_categories();$regions=get_terms(array('taxonomy'=>'job_location_region','hide_empty'=>false,'orderby'=>'name','order'=>'ASC'));echo '<div class="bjm-grid bjm-grid-2"><div><h4>'.esc_html($editing_alert?'Edit Alert':'Add Alert').'</h4><form method="post" class="bjm-submit-job-form">';if($logged_in){wp_nonce_field('bjm_save_job_alert','bjm_save_job_alert_nonce');echo '<input type="hidden" name="alert_id" value="'.esc_attr($editing_alert?$editing_alert->id:0).'"><p><label>Email</label><input type="email" name="alert_email" value="'.esc_attr($editing_alert?$editing_alert->email:wp_get_current_user()->user_email).'" required></p>';}else{wp_nonce_field('bjm_save_guest_job_alert','bjm_save_guest_job_alert_nonce');echo '<input type="hidden" name="manage_token" value="'.esc_attr($editing_alert?$editing_alert->manage_token:'').'"><p><label>Email</label><input type="email" name="alert_email" value="'.esc_attr($editing_alert?$editing_alert->email:'').'" required></p>';}echo '<p><label>Keyword</label><input type="text" name="alert_keyword" value="'.esc_attr($editing_alert?$editing_alert->keyword:'').'"></p><p><label>Category</label><select name="alert_category"><option value="">Any category</option>';foreach($categories as $term)echo '<option value="'.esc_attr($term->slug).'" '.selected($editing_alert?$editing_alert->category_slug:'',$term->slug,false).'>'.esc_html($term->name).'</option>';echo '</select></p><p><label>Region</label><select name="alert_region"><option value="">Any region</option>';foreach($regions as $term)echo '<option value="'.esc_attr($term->slug).'" '.selected($editing_alert?$editing_alert->region_slug:'',$term->slug,false).'>'.esc_html($term->name).'</option>';echo '</select></p><p><label>Frequency</label><select name="alert_frequency">';foreach(bjm_get_job_alert_frequency_options() as $key=>$label)echo '<option value="'.esc_attr($key).'" '.selected($editing_alert?$editing_alert->frequency:'daily',$key,false).'>'.esc_html($label).'</option>';echo '</select></p><p><label><input type="checkbox" name="alert_active" value="1" '.checked($editing_alert?$editing_alert->status:'active','active',false).'> Alert active</label></p><p><button type="submit" class="button button-primary" name="'.esc_attr($logged_in?'bjm_save_job_alert':'bjm_save_guest_job_alert').'">'.esc_html($editing_alert?'Save Alert':'Create Alert').'</button></p>';if(!$logged_in)echo '<p><small>We will email you a confirmation link and a private manage link.</small></p>';echo '</form></div><div><h4>'.esc_html($logged_in?'Your Alerts':'Manage Your Alerts').'</h4>';
        if($alerts){echo '<ul class="bjm-company-list">';foreach($alerts as $alert){$delete=$logged_in?wp_nonce_url(add_query_arg(array('bjm_tab'=>'alerts','bjm_delete_alert'=>$alert->id),$base_url),'bjm_delete_alert'):add_query_arg(array('bjm_delete_guest_alert'=>$alert->manage_token),$base_url);$edit=$logged_in?add_query_arg(array('bjm_tab'=>'alerts','alert_id'=>$alert->id),$base_url):add_query_arg(array('bjm_guest_alert'=>$alert->manage_token),$base_url);echo '<li><strong>'.esc_html(ucfirst($alert->frequency)).'</strong> — '.esc_html($alert->keyword?$alert->keyword:'All jobs');if($alert->category_slug)echo ' · '.esc_html($alert->category_slug);if($alert->region_slug)echo ' · '.esc_html($alert->region_slug);echo ' <span class="bjm-pill">'.esc_html(ucfirst($alert->status)).'</span> <a href="'.esc_url($edit).'">Edit</a> <a href="'.esc_url($delete).'">Delete</a>';if(!$logged_in&&!empty($alert->verified_at))echo ' <span class="bjm-pill">Verified</span>';if($alert->last_sent_at)echo '<br><small>Last sent: '.esc_html(mysql2date(get_option('date_format').' '.get_option('time_format'),$alert->last_sent_at)).'</small>';echo '</li>';}echo '</ul>';}else echo '<p>'.esc_html($logged_in?'No job alerts yet.':'No guest alerts to manage yet. Use the form to create one.').'</p>';echo '</div></div>'; }
}
