<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class BJM_Job_Alerts {
    public static function init() { add_action( 'init', array( __CLASS__, 'handle_actions' ) ); }
    public static function handle_actions() {
        if(isset($_GET['bjm_verify_alert']))self::verify_guest_alert(sanitize_text_field(wp_unslash($_GET['bjm_verify_alert'])));
        if(isset($_GET['bjm_delete_guest_alert']))self::delete_guest_alert(sanitize_text_field(wp_unslash($_GET['bjm_delete_guest_alert'])));
        if(!empty($_POST['bjm_save_guest_job_alert']))self::save_guest_alert();
        if(!is_user_logged_in())return;
        if(empty($_POST['bjm_save_job_alert'])&&empty($_GET['bjm_save_job'])&&empty($_GET['bjm_unsave_job'])&&empty($_GET['bjm_delete_alert']))return;
        if(isset($_GET['bjm_save_job'],$_GET['_wpnonce'])&&wp_verify_nonce(sanitize_text_field(wp_unslash($_GET['_wpnonce'])),'bjm_save_job')){$job_id=absint($_GET['bjm_save_job']);bjm_save_job_for_user($job_id);if(class_exists('BJM_Job_Stats'))BJM_Job_Stats::track_save($job_id);bjm_add_notice('Job saved successfully.');wp_safe_redirect(remove_query_arg(array('bjm_save_job','_wpnonce')));exit;}
        if(isset($_GET['bjm_unsave_job'],$_GET['_wpnonce'])&&wp_verify_nonce(sanitize_text_field(wp_unslash($_GET['_wpnonce'])),'bjm_unsave_job')){bjm_unsave_job_for_user(absint($_GET['bjm_unsave_job']));bjm_add_notice('Job removed from saved jobs.');wp_safe_redirect(remove_query_arg(array('bjm_unsave_job','_wpnonce')));exit;}
        if(isset($_GET['bjm_delete_alert'],$_GET['_wpnonce'])&&wp_verify_nonce(sanitize_text_field(wp_unslash($_GET['_wpnonce'])),'bjm_delete_alert')){global $wpdb;$table=$wpdb->prefix.'bjm_job_alerts';$wpdb->delete($table,array('id'=>absint($_GET['bjm_delete_alert']),'user_id'=>get_current_user_id()),array('%d','%d'));bjm_add_notice('Job alert deleted.');wp_safe_redirect(remove_query_arg(array('bjm_delete_alert','_wpnonce')));exit;}
        if(empty($_POST['bjm_save_job_alert']))return;
        if(!isset($_POST['bjm_save_job_alert_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['bjm_save_job_alert_nonce'])),'bjm_save_job_alert'))return;
        global $wpdb;$table=$wpdb->prefix.'bjm_job_alerts';$alert_id=absint($_POST['alert_id']??0);$data=array('user_id'=>get_current_user_id(),'email'=>sanitize_email(wp_unslash($_POST['alert_email']??wp_get_current_user()->user_email)),'keyword'=>sanitize_text_field(wp_unslash($_POST['alert_keyword']??'')),'category_slug'=>sanitize_title(wp_unslash($_POST['alert_category']??'')),'region_slug'=>sanitize_title(wp_unslash($_POST['alert_region']??'')),'frequency'=>in_array(wp_unslash($_POST['alert_frequency']??'daily'),array_keys(bjm_get_job_alert_frequency_options()),true)?sanitize_key(wp_unslash($_POST['alert_frequency'])):'daily','status'=>!empty($_POST['alert_active'])?'active':'paused','manage_token'=>'','verify_token'=>'','verified_at'=>current_time('mysql'));
        if($alert_id){$existing=bjm_get_job_alert($alert_id);if(!$existing)bjm_add_notice('That alert could not be updated.','error');else{$wpdb->update($table,$data,array('id'=>$alert_id,'user_id'=>get_current_user_id()));bjm_add_notice('Job alert updated.');}}else{$data['created_at']=current_time('mysql');$wpdb->insert($table,$data);bjm_add_notice('Job alert created.');}
        $redirect=bjm_get_page_url('candidate_dashboard_page_id')?:wp_get_referer()?:home_url('/');wp_safe_redirect(add_query_arg('bjm_tab','alerts',$redirect));exit;
    }
    private static function save_guest_alert() {
        if(!isset($_POST['bjm_save_guest_job_alert_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['bjm_save_guest_job_alert_nonce'])),'bjm_save_guest_job_alert'))return;
        global $wpdb;$table=$wpdb->prefix.'bjm_job_alerts';$email=sanitize_email(wp_unslash($_POST['alert_email']??''));if(!is_email($email)){wp_safe_redirect(add_query_arg('bjm_notice','guest_alert_invalid',wp_get_referer()?:home_url('/')));exit;}
        $data=array('user_id'=>0,'email'=>$email,'keyword'=>sanitize_text_field(wp_unslash($_POST['alert_keyword']??'')),'category_slug'=>sanitize_title(wp_unslash($_POST['alert_category']??'')),'region_slug'=>sanitize_title(wp_unslash($_POST['alert_region']??'')),'frequency'=>in_array(wp_unslash($_POST['alert_frequency']??'daily'),array_keys(bjm_get_job_alert_frequency_options()),true)?sanitize_key(wp_unslash($_POST['alert_frequency'])):'daily');$manage_token=sanitize_text_field(wp_unslash($_POST['manage_token']??''));$redirect=bjm_get_page_url('candidate_dashboard_page_id')?:wp_get_referer()?:home_url('/');
        if($manage_token){$existing=bjm_get_guest_alert_by_manage_token($manage_token);if(!$existing){wp_safe_redirect(add_query_arg('bjm_notice','guest_alert_invalid',$redirect));exit;}$data['status']=!empty($_POST['alert_active'])?'active':'paused';$wpdb->update($table,$data,array('id'=>(int)$existing->id));wp_safe_redirect(add_query_arg(array('bjm_guest_alert'=>$existing->manage_token,'bjm_notice'=>'guest_alert_saved'),$redirect));exit;}
        $data['status']='pending';$data['manage_token']=wp_generate_password(24,false,false);$data['verify_token']=wp_generate_password(32,false,false);$data['created_at']=current_time('mysql');$wpdb->insert($table,$data);$alert=bjm_get_guest_alert_by_manage_token($data['manage_token']);if($alert)self::send_guest_verification_email($alert);wp_safe_redirect(add_query_arg('bjm_notice','guest_alert_verify_sent',$redirect));exit;
    }
    private static function send_guest_verification_email($alert){if(empty($alert->email)||empty($alert->verify_token))return;$verify_url=bjm_get_verify_alert_url($alert);$manage_url=bjm_get_manage_alert_url($alert);wp_mail($alert->email,'Confirm your job alert',"Thanks for creating a job alert.\n\nConfirm it here:\n{$verify_url}\n\nOnce confirmed, you can manage it here:\n{$manage_url}\n");}
    private static function verify_guest_alert($token){global $wpdb;$alert=bjm_get_guest_alert_by_verify_token($token);$redirect=bjm_get_page_url('candidate_dashboard_page_id')?:home_url('/');if(!$alert){wp_safe_redirect(add_query_arg('bjm_notice','guest_alert_invalid',$redirect));exit;}$table=$wpdb->prefix.'bjm_job_alerts';$wpdb->update($table,array('status'=>'active','verify_token'=>'','verified_at'=>current_time('mysql')),array('id'=>(int)$alert->id));wp_safe_redirect(add_query_arg(array('bjm_notice'=>'guest_alert_verified','bjm_guest_alert'=>$alert->manage_token),$redirect));exit;}
    private static function delete_guest_alert($token){global $wpdb;$alert=bjm_get_guest_alert_by_manage_token($token);$redirect=bjm_get_page_url('candidate_dashboard_page_id')?:home_url('/');if(!$alert){wp_safe_redirect(add_query_arg('bjm_notice','guest_alert_invalid',$redirect));exit;}$wpdb->delete($wpdb->prefix.'bjm_job_alerts',array('id'=>(int)$alert->id),array('%d'));wp_safe_redirect(add_query_arg('bjm_notice','guest_alert_deleted',$redirect));exit;}
    public static function process_scheduled_alerts(){global $wpdb;$table=$wpdb->prefix.'bjm_job_alerts';$alerts=$wpdb->get_results("SELECT * FROM {$table} WHERE status = 'active'");if(empty($alerts))return;foreach($alerts as $alert){$days='weekly'===$alert->frequency?7:1;$last_ts=$alert->last_sent_at?strtotime($alert->last_sent_at):0;if($last_ts&&$last_ts>(time()-DAY_IN_SECONDS*$days+HOUR_IN_SECONDS))continue;$jobs=self::find_matching_jobs($alert,$days);if(empty($jobs))continue;$subject=sprintf('%s job alert: %d new match%s','weekly'===$alert->frequency?'Weekly':'Daily',count($jobs),count($jobs)===1?'':'es');wp_mail($alert->email,$subject,self::build_email_body($jobs,$alert));if(class_exists('BJM_Job_Stats'))foreach($jobs as $job)BJM_Job_Stats::track_alert_send($job->ID);$wpdb->update($table,array('last_sent_at'=>current_time('mysql')),array('id'=>(int)$alert->id),array('%s'),array('%d'));}}
    private static function find_matching_jobs($alert,$days){$date_after=gmdate('Y-m-d H:i:s',time()-DAY_IN_SECONDS*max(1,absint($days)));$tax_query=array();if(!empty($alert->category_slug))$tax_query[]=array('taxonomy'=>'job_category','field'=>'slug','terms'=>sanitize_title($alert->category_slug));if(!empty($alert->region_slug))$tax_query[]=array('taxonomy'=>'job_location_region','field'=>'slug','terms'=>sanitize_title($alert->region_slug));if(count($tax_query)>1)$tax_query['relation']='AND';$query_args=array('post_type'=>'job_listing','post_status'=>'publish','posts_per_page'=>20,'s'=>sanitize_text_field($alert->keyword),'date_query'=>array(array('after'=>$date_after,'inclusive'=>true)),'meta_query'=>array('relation'=>'AND',array('relation'=>'OR',array('key'=>'_bjm_archived','compare'=>'NOT EXISTS'),array('key'=>'_bjm_archived','value'=>'1','compare'=>'!='))));if(!empty($tax_query))$query_args['tax_query']=$tax_query;return get_posts($query_args);}
    private static function build_email_body($jobs,$alert){$lines=array('Here are the latest jobs matching your alert:','');foreach($jobs as $job){$lines[]=get_the_title($job->ID);$lines[]=get_permalink($job->ID);$company=(string)get_post_meta($job->ID,'_bjm_company_name',true);$location=(string)get_post_meta($job->ID,'_bjm_location_text',true);if($company||$location)$lines[]=trim($company.($company&&$location?' · ':'').$location);$lines[]='';}$lines[]='Manage this alert:';$lines[]=bjm_get_manage_alert_url($alert);return implode("\n",$lines);}
}
